services:
  _defaults:
    autowire: true
    autoconfigure: true

  PositiveDigits\:
    resource: '../../'

  PositiveDigits\Routing\ProductFlowRouteScope:
    autoconfigure: false
    tags:
      - shopware.route_scope